default_language_version:
    python: python3.10.13

repos:
    - repo: local
      hooks:
          - id: autopep8
            name: autopep8
            entry: poetry run autopep8
            language: system
            types: [file, python]
    - repo: https://github.com/python-poetry/poetry
      rev: "1.6.1"
      hooks:
          - id: poetry-lock
            args: [--no-update]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/crate-ci/typos
      rev: v1.16.24
      hooks:
          - id: typos
