default_language_version:
    python: python3.10.13
repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        name: autopep8
        entry: poetry run autopep8
        language: system
        types: [file, python]
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'
    hooks:
    -   id: poetry-lock
        args: [--no-update]