name: Tests

on:
  push:
    branches: [main]
    paths: ['**.py', '**.yaml', '**.yml', 'poetry.lock']
  pull_request:
    branches: [main]
    paths: ['**.py', '**.yaml', '**.yml', 'poetry.lock']

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry=='1.6.1'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'poetry' 
    - name: Install dependencies
      run: poetry install

    - name: Testing
      run: poetry run pytest --verbose
    - name: Linting
      run: poetry run flake8
